version: "3"

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-db
    ports:
    - "7474:7474"
    - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/Test123!
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["apoc","graph-data-science"]
    volumes:
      - ./plugins:/plugins
